setup commit
dckntm/upbad pull request #2
Opened 2022-03-19 12:29 UTC by 24eeeee

2022-03-19 12:49 UTC, Handlest approved these changes
Looks great

2022-03-19 21:08 UTC, katunilya requested changes
Из того, что не указал в других комментариях

1. `README.md` как будто не отформатирован. Не клонил, но подозреваю, что мой форматтер в VS Code (расширение Markdown All in One) перелопатит нехило;
2. К вставкам кода в Markdown: это вкусовщина, но я предпочитаю отдельно выделять code blocks через ```, а не табами, т.к. в некоторых языках и технологиях (в том же python), табы очень важны + через них ты не указываешь, какой именно язык тебе использовать при рендеринге подсветки;
3. КМК лучше держать проект в "именной" папке, а не в `src` иначе потом импорты все будут выглядеть как `from src.api.router import Router`. `src` не несет вообще никакой смысловой нагрузки и при наличии нескольких параллельных проектов только будет запутывать. Поэтому я бы переименовал папку из `src` в `upbad`. Альтернативно внутри `src` оставить `wsgi.py`, как точку входа для сервера, на котором приложение будет запускаться (`gunicorn`), а уже код писать внутри `src` в модуле под проект с нужным названием. Я как правило живу с первым вариантом;
4. Добавить `__init__.py` в корни исходника, иначе потом он не будет считаться пакетом; 

---

P.S. мем зачитан 

![image](https://user-images.githubusercontent.com/40162026/159138346-1c2119f2-c4b1-4df4-a9d2-ec003ab1a6a2.png)

2022-03-19 21:08 UTC, katunilya commented on requirements.txt
> +Werkzeug==2.0.3
не хватает `black`а

2022-03-19 21:08 UTC, katunilya commented on README.md
> +	$ -m pip install -r requirements.txt
тут либо не нужно `-m` либо `python` в начало нужно добавить

2022-03-19 21:08 UTC, katunilya commented on tests/sample_test.py
> +assert sample_test_false() is False
Тесты немного не так пишуется.

Тест - отдельная функция, которая считается успешной, если выполнена без ошибок. Тест ничего не возвращает. 

Конструкция `assert` в Python выкидывает ошибку (`AssertionError` кажется), если выражение внутри является `False`. Подробнее можно почитать на [RealPython](https://realpython.com/python-assert-statement/).

Соответсвенно `assert` должен вызываться в функции, а не вне ее.

```python
def f(x: int) -> int:
   return x * 2 + 1

def test_f():
   result = f(1)

   assert result == 2
```

А еще функции для тестов должны начинаться со слова `test`. По крайней мере негласно как правило делают так.

2022-03-19 21:08 UTC, katunilya commented on README.md
> +	flask run
Если начинаете использовать `$`, то используйте его до конца 😄.

Знак `$` в сниппетах кода значит, что то, что идет дальше должно быть выполнено непосредственно в терминале, поэтому можно смело добавлять его перед `set ...`, `export ...` и `flask run`.

А еще для удобства сниппеты на Windows и Linux лучше разибть на отдельные блоки кода, чтобы потом при клонировании можно было просто нажать на кнопочку копирования в правом углу на GitHub, а не выделять отдельно строчку.

2022-03-19 21:08 UTC, katunilya commented on requirements.txt
> +Werkzeug==2.0.3
Ну и соответственно python код в его отсутствие тоже как будто не отформатирован

2022-03-19 21:14 UTC, katunilya commented
А и по именованию веток я думаю стоит договориться. Есть куча всяких flow для git, но нам что-то сложное не надо, так что можно просто именовать по принципу `<issue-number>-<issue-description>`, т.е. например для этой задачи нужно было бы сделать что-то типа `1-setup-basic-flask-project`

2022-03-21 13:11 UTC, 24eeeee commented on README.md
> +	$ -m pip install -r requirements.txt
done

2022-03-21 13:16 UTC, 24eeeee commented on README.md
> +	flask run
done

2022-03-21 13:24 UTC, 24eeeee commented on tests/sample_test.py
> +assert sample_test_false() is False
suppose it's done for now, but i wouldn't resolve it 'til i read the article))

2022-03-21 13:24 UTC, 24eeeee commented on tests/sample_test.py
> +assert sample_test_false() is False
так, стоп, а зачем я латиницу насилую вообще тут????

2022-03-21 17:10 UTC, katunilya approved these changes

2022-03-26 08:56 UTC, merged